apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-secret
  namespace: monitoring
type: Opaque
stringData:
  slack-webhook-url: https://hooks.slack.com/services/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