vpc_name        = "socks-shop-vpc"
region          = "lon1"
vpc_cidr        = "10.0.0.0/16"
vpc_description = "VPC for Socks Shop microservice"
firewall_name = "socks-shop-firewall"
registry_name     = "socks-shop-registry"
subscription_tier = "basic"